# Generated by Django 5.1.6 on 2025-03-04 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('cedula', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Cédula del Representante')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Representante')),
            ],
            options={
                'verbose_name': 'Representante',
                'verbose_name_plural': 'Representantes',
                'db_table': 'representante',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Paciente')),
                ('cedula', models.CharField(max_length=20, verbose_name='Cédula del Paciente')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad del Paciente')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono del Paciente')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Sexo del Paciente')),
                ('estado_civil', models.BooleanField(choices=[(True, 'Casado'), (False, 'Soltero')], verbose_name='Estado Civil')),
                ('ocupacion', models.CharField(max_length=100, verbose_name='Ocupación del Paciente')),
                ('cedula_representante', models.ForeignKey(db_column='cedula_representante', on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='odontologia_app.representante', verbose_name='Cédula del Representante')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
            },
        ),
    ]
