# Generated by Django 5.1.6 on 2025-03-04 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(default='', max_length=100, verbose_name='Nombre del Paciente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cedula_representante',
            field=models.ForeignKey(blank=True, db_column='cedula_representante', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='odontologia_app.representante', verbose_name='Cédula del Representante'),
        ),
    ]
