# Generated by Django 5.1.6 on 2025-03-05 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia_app', '0004_remove_usuario_contraseña_remove_usuario_rol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia_Medica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('examinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Examinador')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontologia_app.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Historia_Medica',
                'verbose_name_plural': 'Historias_Medicas',
            },
        ),
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diabetes', models.BooleanField(default=False, verbose_name='Diabetes')),
                ('tbc', models.BooleanField(default=False, verbose_name='T.B.C.')),
                ('hipertension', models.BooleanField(default=False, verbose_name='Hipertensión')),
                ('artritis', models.BooleanField(default=False, verbose_name='Artritis')),
                ('alergias', models.BooleanField(default=False, verbose_name='Alergias')),
                ('neuralgias', models.BooleanField(default=False, verbose_name='Neuralgias')),
                ('hemorragias', models.BooleanField(default=False, verbose_name='Hemorragias')),
                ('hepatitis', models.BooleanField(default=False, verbose_name='Hepatitis')),
                ('sinusitis', models.BooleanField(default=False, verbose_name='Sinusitis')),
                ('trastorno_mentales', models.BooleanField(default=False, verbose_name='Trastornos Mentales')),
                ('enfermedades_eruptivas', models.BooleanField(default=False, verbose_name='Enfermedades Eruptivas')),
                ('enfermedades_renales', models.BooleanField(default=False, verbose_name='Enfermedades Renales')),
                ('parotiditis', models.BooleanField(default=False, verbose_name='Parotiditis')),
                ('historia_medica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesis', to='odontologia_app.historia_medica', verbose_name='Historia Médica')),
            ],
            options={
                'verbose_name': 'Anamnesis',
                'verbose_name_plural': 'Anamnesis',
            },
        ),
    ]
