# Generated by Django 5.1.6 on 2025-03-05 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia_app', '0005_historia_medica_anamnesis'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesFamiliares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('P', 'Paternos'), ('M', 'Maternos'), ('A', 'Ambos')], max_length=1, verbose_name='Tipo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontologia_app.anamnesis', verbose_name='Anamnesis')),
            ],
            options={
                'verbose_name': 'Antecedente Familiar',
                'verbose_name_plural': 'Antecedentes Familiares',
            },
        ),
        migrations.CreateModel(
            name='Habitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('anamnesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odontologia_app.anamnesis', verbose_name='Anamnesis')),
            ],
            options={
                'verbose_name': 'Hábito',
                'verbose_name_plural': 'Hábitos',
            },
        ),
    ]
