# Generated by Django 5.1.6 on 2025-03-06 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odontologia_app', '0006_antecedentesfamiliares_habitos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedentesfamiliares',
            name='anamnesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_familiares', to='odontologia_app.anamnesis', verbose_name='Anamnesis'),
        ),
        migrations.AlterField(
            model_name='habitos',
            name='anamnesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to='odontologia_app.anamnesis', verbose_name='Anamnesis'),
        ),
    ]
